#!/usr/bin/env bash
set -e

# ---------------------------------------------------------
# GitHub Copilot test generation (LOCAL ONLY)
# Jenkins / CI will skip this script automatically
# ---------------------------------------------------------

if [ "$CI" = "true" ]; then
  echo "CI environment detected. Skipping Copilot test generation."
  exit 0
fi

# --- Preconditions -----------------------------------------------------------

if ! command -v gh >/dev/null 2>&1; then
  echo "GitHub CLI (gh) not found. Please install gh."
  exit 1
fi

if ! gh copilot --help >/dev/null 2>&1; then
  echo "GitHub Copilot CLI not installed."
  echo "Run: gh extension install github/gh-copilot"
  exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not inside a Git repository."
  exit 1
fi

# --- Configuration -----------------------------------------------------------

SRC_DIR="src"
TEST_DIR="tests"
GENERATED_COUNT=0

echo "Generating Jest .spec.js files using GitHub Copilot..."

mkdir -p "$TEST_DIR"

# --- Generate tests (FIXED LOOP) ---------------------------------------------

while read -r srcFile; do

  specFile=$(echo "$srcFile" \
    | sed "s|^$SRC_DIR|$TEST_DIR|" \
    | sed "s|\.js$|\.spec.js|")

  if [ -f "$specFile" ]; then
    echo "Skipping existing test: $specFile"
    continue
  fi

  mkdir -p "$(dirname "$specFile")"

  echo "Generating: $specFile"

  gh copilot suggest "
Generate Jest unit tests for this Node.js JavaScript file.

Rules:
- Use jest
- Mock external dependencies
- Cover success, failure, and edge cases
- Use describe and it blocks
- Output ONLY valid JavaScript code
- No markdown, no explanations

Source code:
$(cat "$srcFile")
" --language javascript > "$specFile"

  GENERATED_COUNT=$((GENERATED_COUNT + 1))

done < <(find "$SRC_DIR" -type f -name "*.js" ! -name "*.spec.js")

# --- Git commit & push --------------------------------------------------------

if [ "$GENERATED_COUNT" -eq 0 ]; then
  echo "No new test files generated. Nothing to commit."
  exit 0
fi

echo "Generated $GENERATED_COUNT new test file(s)."

echo "Staging test files..."
git add "$TEST_DIR"

if git diff --cached --quiet; then
  echo "No changes detected after staging."
  exit 0
fi

COMMIT_MSG="test: add Jest unit tests generated by GitHub Copilot"

echo "Committing changes..."
git commit -m "$COMMIT_MSG"

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Pushing to origin/$CURRENT_BRANCH..."
git push origin "$CURRENT_BRANCH"

echo "AI test generation + Git push completed successfully."
